### ISSUE TITLE
React Native link command will result in "Cannot get property 'xxxx'... " with a standard React Native setup.

### ISSUE THREAD

**Issue by trustfall** [cobrowseio/cobrowse-sdk-react-native#1] opened 2018-10-18 19:50 UTC
The React Native SDK will fail out of the gate on android in a lot of cases, as a standard React Native setup does not include the `ext` property in the `android/build.gradle` file, and will have the version requirements all declared in `android/app/build.gradle`. This will cause errors for people trying to sync/build, stating:

`Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist.`

It may make more sense to define an actual compile version in the library itself, or at the very least give users instructions to add `ext` to the proper file, along with swapping values to `rootProject.ext.xxxx` in `app/build.gradle`.

**Comment by trustfall** [comment] 2018-10-19 17:29
Awesome, I've modified my project to mirror your original, I just thought it might be a pain point for some people. Thank you for the quick response! Also, I seem to be having trouble with linking iOS, I've manually added the iOS cobrowse framework from the iOS SDK, and manually linked the library, but I'm getting errors stating `libRCTCobrowseIO.a` cannot be found. Are there manually linking instructions somewhere, or am I doing something wrong? My react-native link command has been working intermittently lately and I'd prefer to do it manually. 

I'm adding the iOS framework to my project, going into node modules, into the `ios` folder and taking the `.xcodeproj` file and pulling it into my libraries, then moving over the `libRCTCobrowseIO.a` file into the `Link Binaries with Libraries` section of Build phases, like a standard React Native project.

**Comment by trustfall** [comment] 2018-10-19 21:14
Just updating here - I was able to link by manually entering in:
`pod 'cobrowse-sdk-react-native', :path => '../node_modules/cobrowse-sdk-react-native'`
into my Podfile, and running `pod install` form the ios folder. I manually linked the libs from above, everything seemed to run okay, but now I am getting: 
![image](https://user-images.githubusercontent.com/8658751/47244128-a1ade380-d3b1-11e8-8889-6fe2a76cb9a9.png)

**Comment by headlessme** [comment] 2018-10-23 06:37
Is there a reason not to let Pods set up the linking itself if you're already using that? There's an example Podfile [here](https://github.com/cobrowseio/cobrowse-sdk-react-native/blob/master/Example/ios/Podfile) that works for building Cobrowse into a RN project. 

The process for manually linking the Cobrowse React Native module is:
1. Add the SocketIO and Starscream frameworks (dependencies of CobrowseIO framework) to your Xcode project
2. Add the CobrowseIO framework to your Xcode project
3. Make sure these frameworks are included in the Embedded Binaries section of your Xcode project settings so they're available in the final build product
4. Make sure the Swift runtime is built into your Xcode project products ("Always Embed Swift Standard Libraries")
5. Add the cobrowse-sdk-react-native Xcode project as a dependency of your Xcode project (drag into the list of other Xcode projects as usual)
6. Add the three frameworks above as dependencies of the RCTCobrowseIO target in the Link Binary With Libraries section of the cobrowse-sdk-react-native Xcode project
6. Set up the Link Binary With Libraries step for the including the libRCTCobrowseIO.a build product into your Xcode project

Although this should work, we'd strongly recommend using a proper dependency manager to make upgrades simpler, and making sure version dependencies are properly satisfied :) All that should be required when using Pods as in our example to to make sure the appropriate line is added to your Podfile.

**Comment by trustfall** [comment] 2018-10-23 17:28
yeah, I've tried `pod install` by itself and I get a list of over 200 issues:
![image](https://user-images.githubusercontent.com/8658751/47378829-7e877a80-d6b6-11e8-8127-5e755ca44133.png)
it appears that the podfile is installing all the required information:
```
Installing CobrowseIO (1.6.1)
Installing Socket.IO-Client-Swift (13.2.1)
Installing Starscream (3.0.6)
Installing cobrowse-sdk-react-native (1.1.5)
```

**Comment by headlessme** [comment] 2018-10-23 17:49
Oh wow, are those all Cobrowse related errors or react native issues? It's worth noting that before RN 0.57ish building via pods with `use_frameworks!` was quite broken, so upgrading your RN version might fix quite a few of them. Which RN version are you currently running?

**Comment by trustfall** [comment] 2018-10-23 18:53
0.51 - updating react native may be quite a headache as we're using many third party SDKs and libraries.

**Comment by trustfall** [comment] 2018-10-23 18:57
and yes, those are all related to co-browse.

**Comment by trustfall** [comment] 2018-10-23 20:01
do you have any other suggestions other than updating React Native?

**Comment by headlessme** [comment] 2018-10-24 03:29
Ok, if upgrading RN isn't an option for you right now, then it should still be possible to manually add all the required components to your project. The process should be fairly similar to what I mentioned above. I've tried out the process and it worked for me on a newer RN version, I'll try with RN 0.51 and see if there's any big differences and let you know.

**Comment by headlessme** [comment] 2018-10-24 04:56
I've had a go at building Cobrowse into a RN 0.51 project, and it works when using roughly the process above. Some things to note: 

- RN 0.51 is broken with the newer versions of Xcode, so I had to use [this](https://github.com/rhdeck/react-native-fix-xcode-10) to get the default 0.51 project to build and run.
- I included the projects to build SocketIO and Starscream from source as this is closer to what you'll need to do if you want to have the versions managed by Pods. 
- Cobrowse SDK was still included as a prebuilt Framework.
- I wasn't using Pods at all in this test so there might be some differences from your setup that I haven't encountered. If you'd like me to take a look at them could you share your Podfile with me?

**Comment by trustfall** [comment] 2018-10-25 20:02
so the problem is definitely with `Socket.IO-Client-Swift` - part of the issue here possibly may be, when using a podfile, is that it's using `use_frameworks!` which from what I've read isn't really supported with RN. I was able to different results if I used this, along with the proper pre-install and post-install scripts within the podfile, but the problem is that it blows up a ton of other SDKs and libraries that also exist within the same podfile. I'm gonna play around with it a bit more and see what I can do.

**Comment by headlessme** [comment] 2018-10-25 23:56
Yea, RN before 0.56 or 0.57 is very broken when using the the `use_frameworks!` flag, so I'd suggest not using that at all until you are able to upgrade to one of those versions. This probably means you can't install the dependencies using Pods yet and will have to import the projects manually as I did above. You can still link the frameworks built by those projects manually without using the use_frameworks flag.

**Comment by trustfall** [comment] 2018-10-26 17:21
Would it make sense to have an installation guide for those users who aren't using RN 0.57 yet, considering it was only released last month? I would assume many mature RN projects are not going to be up to this version, and also have a variety of other third party tools implemented, and will run into these same issues.

**Comment by headlessme** [comment] 2018-10-27 04:45
Yea we definitely need some better documentation around supported RN versions. Luckily this hasn't been as issue for our existing RN clients so far, as you can probably tell you guys are the first to hit it!

**Comment by headlessme** [comment] 2018-10-28 18:03
Yea I agree we definitely need some better documentation around supported RN versions!

**Comment by headlessme** [comment] 2018-10-31 10:34
Just wanted to check in and see if you managed to resolve the build issues here?

**Comment by trustfall** [comment] 2018-10-31 14:22
I'm actually just in the middle of updating everything so this took a backseat until today - looks like even with RN version 0.57, pods has the same issues (it doesn't seem to be specific to co-browse libs, but others that have issues with `use_frameworks!`), Just curious, how did you go about including SocketIO from source? I have to circle back to this, but I didn't see any mention of building from source in the SocketIO-Swift docs, and last time I received some errors when trying to add it manually to the project.

**Comment by headlessme** [comment] 2018-11-01 09:17
We've managed to simplify the process to add Cobrowse without requiring pods, you'll need to upgrade to 1.1.6 of the npm package, and then:

1. Add the SocketIO and Starscream projects to your Xcode project.
2. Add CobrowseIO framework under to the ios folder (same folder as your project)
3. Add the CobrowseIO, SocketIO and Starscream frameworks to the Link Binary With Libraries of your project
4. Add the CobrowseIO, SocketIO and Starscream frameworks to the Embedded Binaries section of your Xcode project settings.

**Comment by headlessme** [comment] 2019-04-29 12:22
We've added support for Carthage as an alternate to using Pods. To use Carthage:
1. Add a "Cartfile" in the same folder as your Xcode project file containing:
`github "cobrowseio/cobrowse-sdk-ios-binary"`
2. Run carthage update from the command line in the same folder as the Cartfile. This should download and build the three dependencies, something like:
```
*** Fetching cobrowse-sdk-ios-binary
*** Fetching socket.io-client-swift
*** Fetching Starscream
```
3. Open your Xcode project, add the following Frameworks to the Embedded Binaries section (they will be in ./Carthage/Build/iOS/ in the same directory as your Cartfile):
CobrowseIO.framework
Starscream.framework
SocketIO.framework

As there's now an alternative which doesn't require Pods I'm going to close this issue. Please reopen if there's anything we've missed.

**Closed by headlessme** 2019-04-29 12:22 UTC

**Comment by KowalskiP** [comment] 2019-09-24 03:08
Hi, I am using your library and I have question about this Pods and Carthage libraries.
My application is including both pods and carts libraries and I am trying to figure out which library I can remove.
Application without carthage library will not work, however when I remove pod requirement, cobrowse is not defined in RN.
What did I miss?

**Comment by headlessme** [comment] 2019-09-25 07:18
We've never tried running a project with both Pods and Carthage, so I'm not sure what the process would be for that. I'd recommend checking that the framework is actually included in the project if you're using Carthage. If you believe this is caused by a bug in Cobrowse, please open a new issue.
